#!/bin/bash

dub build :100-doors-1
dub build :100-doors-2
dub build :24-game
dub build :24-game-solve
dub build :9-billion-names-of-God-the-integer
dub build :99-Bottles-of-Beer
dub build :A+B
dub build :ABC-Problem
dub build :AKS-test-for-primes
dub build :Abstract-type
dub build :Abundant-deficient-and-perfect-number-classifications
dub build :Accumulator-factory
dub build :Ackermann-function
dub build :Add-a-variable-to-a-class-instance-at-runtime
dub build :Address-of-a-variable
dub build :Align-columns
dub build :Aliquot-sequence-classifications
dub build :Almost-prime
dub build :Amb
dub build :Amicable-pairs
dub build :Anagrams-Deranged-anagrams
dub build :Animation
dub build :Anonymous-recursion
dub build :Apply-a-callback-to-an-array
dub build :Arbitrary-precision-integers-included
dub build :Arithmetic-Complex
dub build :Arithmetic-Integer
dub build :Arithmetic-Rational
dub build :Arithmetic-evaluation
dub build :Arithmetic-geometric-mean
dub build :Array-concatenation
dub build :Arrays
dub build :Assertions
dub build :Associative-array-Creation
dub build :Associative-array-Iteration
dub build :Atomic-updates
dub build :Average-loop-length
dub build :Averages-Arithmetic-mean
dub build :Averages-Mean-angle
dub build :Averages-Mean-time-of-day
dub build :Averages-Median
dub build :Averages-Mode
dub build :Averages-Pythagorean-means
dub build :Averages-Root-mean-square
dub build :Averages-Simple-moving-average
dub build :Balanced-brackets
dub build :Balanced-ternary
dub build :Benfords-law
dub build :Bernoulli-numbers
dub build :Best-shuffle
dub build :Binary-digits
dub build :Binary-search
dub build :Binary-strings
dub build :Bitcoin-address-validation
dub build :Bitcoin-public-point-to-address
dub build :Bitmap
dub build :Bitmap-B-zier-curves-Cubic
dub build :Bitmap-B-zier-curves-Quadratic
dub build :Bitmap-Bresenhams-line-algorithm
dub build :Bitmap-Flood-fill
dub build :Bitmap-Histogram
dub build :Bitmap-Midpoint-circle-algorithm
dub build :Bitwise-IO
dub build :Bitwise-operations
dub build :Box-the-compass
dub build :Brownian-tree
dub build :Bulls-and-cows
dub build :Bulls-and-cows-Player
dub build :CRC-32
dub build :CSV-data-manipulation
dub build :CSV-to-HTML-translation
dub build :Caesar-cipher
dub build :Calendar
dub build :Calendar-for-real-programmers
dub build :Call-a-foreign-language-function
dub build :Call-a-function
dub build :Call-a-function-in-a-shared-library
dub build :Call-an-object-method
dub build :Canny-edge-detector
dub build :Carmichael-3-strong-pseudoprimes
dub build :Case-sensitivity-of-identifiers
dub build :Casting-out-nines
dub build :Catalan-numbers
dub build :Catalan-numbers-Pascals-triangle
dub build :Catamorphism
dub build :Character-codes
dub build :Check-Machin-like-formulas
dub build :Check-that-file-exists
dub build :Checkpoint-synchronization
dub build :Chinese-remainder-theorem
dub build :Cholesky-decomposition
dub build :Circles-of-given-radius-through-two-points
dub build :Classes
dub build :Closest-pair-problem
dub build :Closures-Value-capture
dub build :Collections
dub build :Color-quantization
dub build :Combinations-1
dub build :Combinations-2
dub build :Combinations-3
dub build :Combinations-4
dub build :Combinations-and-permutations
dub build :Combinations-with-repetitions
dub build :Comma-quibbling
dub build :Command-line-arguments
dub build :Comments
dub build :Compare-sorting-algorithms-performance
dub build :Compile-time-calculation
dub build :Compound-data-type
dub build :Concurrent-computing
dub build :Conditional-structures
dub build :Conjugate-transpose
dub build :Constrained-genericity
dub build :Constrained-random-points-on-a-circle
dub build :Continued-fraction
dub build :Convert-decimal-number-to-rational
dub build :Conways-Game-of-Life
dub build :Copy-a-string
dub build :Count-in-factors
dub build :Count-in-octal
dub build :Count-occurrences-of-a-substring
dub build :Count-the-coins
dub build :Create-a-file
dub build :Create-a-two-dimensional-array-at-runtime
dub build :Create-an-HTML-table
dub build :Create-an-object-at-a-given-address
dub build :Currying
dub build :Cut-a-rectangle
dub build :DNS-query
dub build :Date-format
dub build :Day-of-the-week
dub build :Deal-cards-for-FreeCell
dub build :Death-Star
dub build :Deconvolution-1D
dub build :Deconvolution-2D-plus
dub build :Define-a-primitive-data-type
dub build :Delegates
dub build :Delete-a-file
dub build :Detect-division-by-zero
dub build :Determine-if-a-string-is-numeric
dub build :Digital-root
dub build :Digital-root-Multiplicative-digital-root
dub build :dinesmans-multiple-dwelling-problem-1
dub build :dinesmans-multiple-dwelling-problem-2
dub build :Dining-philosophers
dub build :Discordian-date
dub build :Distributed-programming
dub build :Documentation
dub build :Dot-product
dub build :Doubly-linked-list-Definition
dub build :Doubly-linked-list-Element-definition
dub build :Doubly-linked-list-Element-insertion
dub build :Doubly-linked-list-Traversal
dub build :Dragon-curve
dub build :Draw-a-cuboid
dub build :Draw-a-sphere
dub build :Dutch-national-flag-problem
dub build :Echo-server
dub build :Element-wise-operations
dub build :Empty-directory
dub build :Empty-program
dub build :Empty-string
dub build :Enforced-immutability
dub build :Entropy
dub build :Enumerations
dub build :Environment-variables
dub build :Equilibrium-index
dub build :Ethiopian-multiplication
dub build :Euler-method
dub build :Evaluate-binomial-coefficients
dub build :Even-or-odd
dub build :Evolutionary-algorithm
dub build :Exceptions
dub build :Exceptions-Catch-an-exception-thrown-in-a-nested-call
dub build :Execute-HQ9+
dub build :Execute-a-Markov-algorithm
dub build :Execute-a-system-command
dub build :Exponentiation-operator
dub build :Extend-your-language
dub build :Extensible-prime-generator
dub build :Extreme-floating-point-values
dub build :Factorial
dub build :Factors-of-a-Mersenne-number
dub build :Factors-of-an-integer
dub build :Fast-Fourier-transform
dub build :Fibonacci-n-step-number-sequences
dub build :Fibonacci-sequence
dub build :Fibonacci-word
dub build :Fibonacci-word-fractal
dub build :File-input-output
dub build :File-modification-time
dub build :File-size
dub build :Filter
dub build :Find-common-directory-path
dub build :Find-limit-of-recursion
dub build :Find-the-last-Sunday-of-each-month
dub build :Find-the-missing-permutation
dub build :First-class-environments
dub build :First-class-functions
dub build :First-class-functions-Use-numbers-analogously
dub build :Five-weekends
dub build :FizzBuzz
dub build :Flatten-a-list
dub build :Flipping-bits-game
dub build :Flow-control-structures
dub build :Floyds-triangle
dub build :Forest-fire
dub build :Formatted-numeric-output
dub build :Forward-difference
dub build :Four-bit-adder
dub build :Fractal-tree
dub build :Fractran
dub build :Function-composition
dub build :Function-definition
dub build :Function-prototype
dub build :Galton-box-animation
dub build :Gamma-function
dub build :Gaussian-elimination
dub build :generate-chess960-starting-position-1
dub build :generate-chess960-starting-position-2
dub build :generate-chess960-starting-position-3
dub build :Generate-lower-case-ASCII-alphabet
dub build :Generator-Exponential
dub build :Generic-swap
dub build :Globally-replace-text-in-several-files
dub build :Gray-code
dub build :Grayscale-image
dub build :Greatest-common-divisor
dub build :Greatest-element-of-a-list
dub build :Greatest-subsequential-sum
dub build :Guess-the-number
dub build :Guess-the-number-With-feedback
dub build :Guess-the-number-With-feedback--player-
dub build :HTTP
dub build :Hailstone-sequence
dub build :Hamming-numbers
dub build :Happy-numbers
dub build :Harshad-or-Niven-series
dub build :Hash-from-two-arrays
dub build :Hash-join
dub build :Haversine-formula
dub build :Hello-world-Graphical
dub build :Hello-world-Line-printer
dub build :Hello-world-Newbie
dub build :Hello-world-Newline-omission
dub build :Hello-world-Standard-error
dub build :Hello-world-Text
dub build :Hello-world-Web-server
dub build :Here-document
dub build :Heronian-triangles
dub build :Hickerson-series-of-almost-integers
dub build :Higher-order-functions
dub build :History-variables
dub build :Hofstadter-Conway-10000-sequence
dub build :Hofstadter-Figure-Figure-sequences
dub build :Hofstadter-Q-sequence
dub build :Holidays-related-to-Easter
dub build :Horizontal-sundial-calculations
dub build :Horners-rule-for-polynomial-evaluation
dub build :Host-introspection
dub build :Hostname
dub build :Hough-transform
dub build :Huffman-coding
dub build :IBAN
dub build :Identity-matrix
dub build :Image-convolution
dub build :Image-noise
dub build :Include-a-file
dub build :Increment-a-numerical-string
dub build :Infinity
dub build :Inheritance-Multiple
dub build :Inheritance-Single
dub build :Input-loop
dub build :Integer-comparison
dub build :Integer-overflow
dub build :Integer-sequence
dub build :Introspection
dub build :Inverted-index
dub build :Iterated-digits-squaring
dub build :JSON
dub build :Jensens-Device
dub build :Josephus-problem
dub build :K-d-tree
dub build :K-means++-clustering
dub build :Kaprekar-numbers
dub build :Keyboard-input-Flush-the-keyboard-buffer
dub build :Keyboard-input-Keypress-check
dub build :Keyboard-input-Obtain-a-Y-or-N-response
dub build :Knapsack-problem-0-1
dub build :Knapsack-problem-Bounded
dub build :Knapsack-problem-Continuous
dub build :Knapsack-problem-Unbounded
dub build :Knights-tour
dub build :Knuth-shuffle
dub build :Knuths-algorithm-S
dub build :LU-decomposition
dub build :LZW-compression
dub build :Langtons-ant
dub build :largest-int-from-concatenated-ints
dub build :Last-Friday-of-each-month
dub build :Last-letter-first-letter
dub build :Leap-year
dub build :Least-common-multiple
dub build :Left-factorials
dub build :Letter-frequency
dub build :Levenshtein-distance
dub build :Linear-congruential-generator
dub build :List-comprehensions
dub build :Literals-Integer
dub build :Literals-String
dub build :Logical-operations
dub build :Long-multiplication
dub build :Longest-common-subsequence
dub build :Longest-increasing-subsequence
dub build :Longest-string-challenge
dub build :Look-and-say-sequence
dub build :Loop-over-multiple-arrays-simultaneously
dub build :Loops-Break
dub build :Loops-Continue
dub build :Loops-Do-while
dub build :Loops-Downward-for
dub build :Loops-For
dub build :Loops-For-with-a-specified-step
dub build :Loops-Foreach
dub build :Loops-Infinite
dub build :Loops-N-plus-one-half
dub build :Loops-Nested
dub build :Loops-While
dub build :Lucas-Lehmer-test
dub build :Ludic-numbers
dub build :Luhn-test-of-credit-card-numbers
dub build :MD4
dub build :MD5
dub build :MD5-Implementation
dub build :Machine-code
dub build :Mad-Libs
dub build :Magic-squares-of-odd-order
dub build :Main-step-of-GOST-28147-89
dub build :Man-or-boy-test
dub build :Mandelbrot-set
dub build :Map-range
dub build :matrix-arithmetic
dub build :Matrix-exponentiation-operator
dub build :Matrix-multiplication
dub build :Matrix-transposition
dub build :Maximum-triangle-path-sum
dub build :Maze-generation
dub build :Maze-solving
dub build :Median-filter
dub build :Memory-allocation
dub build :Memory-layout-of-a-data-structure
dub build :Menu
dub build :Metaprogramming
dub build :Metered-concurrency
dub build :Middle-three-digits
dub build :Miller-Rabin-primality-test
dub build :Modular-exponentiation
dub build :Modular-inverse
dub build :Monte-Carlo-methods
dub build :Monty-Hall-problem
dub build :Move-to-front-algorithm
dub build :Multifactorial
dub build :Multiple-distinct-objects
dub build :Multiplication-tables
dub build :Multisplit
dub build :Munching-squares
dub build :Mutual-recursion
dub build :n-queens-problem-1
dub build :n-queens-problem-2
dub build :n-queens-problem-3
dub build :Narcissistic-decimal-number
dub build :Natural-sorting
dub build :Nautical-bell
dub build :Non-continuous-subsequences
dub build :Non-decimal-radices-Convert
dub build :Non-decimal-radices-Input
dub build :Non-decimal-radices-Output
dub build :Nth
dub build :Nth-root
dub build :Null-object
dub build :Number-names
dub build :Number-reversal-game
dub build :Numeric-error-propagation
dub build :Numerical-integration
dub build :Numerical-integration-Gauss-Legendre-Quadrature
dub build :Object-serialization
dub build :Odd-word-problem
dub build :Old-lady-swallowed-a-fly
dub build :One-dimensional-cellular-automata
dub build :One-of-n-lines-in-a-file
dub build :OpenGL
dub build :Optional-parameters
dub build :Order-disjoint-list-items
dub build :Order-two-numerical-lists
dub build :Ordered-Partitions
dub build :Ordered-words
dub build :Palindrome-detection
dub build :Pangram-checker
dub build :Paraffins
dub build :Parallel-calculations
dub build :Parametric-polymorphism
dub build :Parsing-RPN-calculator-algorithm
dub build :Parsing-RPN-to-infix-conversion
dub build :Partial-function-application
dub build :Pascals-triangle
dub build :Pascals-triangle-Puzzle
dub build :Penneys-game
dub build :Percentage-difference-between-images
dub build :Percolation-Bond-percolation
dub build :Percolation-Mean-cluster-density
dub build :Percolation-Mean-run-density
dub build :Percolation-Site-percolation
dub build :Perfect-numbers
dub build :Permutation-test
dub build :permutations-1
dub build :permutations-2
dub build :permutations-3
dub build :Permutations-Derangements
dub build :Permutations-Rank-of-a-permutation
dub build :Permutations-by-swapping
dub build :Pernicious-numbers
dub build :Phrase-reversals
dub build :Pi
dub build :Pick-random-element
dub build :Pig-the-dice-game
dub build :Pig-the-dice-game-Player
dub build :Playing-cards
dub build :Pointers-and-references
dub build :Polymorphic-copy
dub build :Polymorphism
dub build :Polynomial-long-division
dub build :Power-set
dub build :Price-fraction
dub build :Primality-by-trial-division
dub build :Prime-decomposition
dub build :Priority-queue
dub build :Probabilistic-choice
dub build :Problem-of-Apollonius
dub build :Program-name
dub build :Program-termination
dub build :Pythagorean-triples
dub build :QR-decomposition
dub build :Quaternion-type
dub build :Queue-Usage
dub build :Quickselect-algorithm
dub build :Quine
dub build :RIPEMD-160
dub build :RSA-code
dub build :Random-numbers
dub build :Range-expansion
dub build :Range-extraction
dub build :Ray-casting-algorithm
dub build :Read-a-configuration-file
dub build :Read-a-file-line-by-line
dub build :Read-a-specific-line-from-a-file
dub build :Read-entire-file
dub build :Real-constants-and-functions
dub build :Reduced-row-echelon-form
dub build :Regular-expressions
dub build :Remove-duplicate-elements
dub build :Remove-lines-from-a-file
dub build :Rename-a-file
dub build :Rendezvous
dub build :Rep-string
dub build :Repeat-a-string
dub build :Resistor-mesh
dub build :Respond-to-an-unknown-method-call
dub build :Return-multiple-values
dub build :Reverse-a-string
dub build :Reverse-words-in-a-string
dub build :Rock-paper-scissors
dub build :Roman-numerals-Decode
dub build :Roman-numerals-Encode
dub build :Roots-of-a-function
dub build :Roots-of-a-quadratic-function
dub build :Roots-of-unity
dub build :Rosetta-Code-Count-examples
dub build :Rosetta-Code-Fix-code-tags
dub build :Rosetta-Code-Rank-languages-by-popularity
dub build :Rot-13
dub build :Run-length-encoding
dub build :Runge-Kutta-method
dub build :S-Expressions
dub build :SEDOLs
dub build :SHA-1
dub build :SHA-256
dub build :Same-Fringe
dub build :Search-a-list
dub build :Secure-temporary-file
dub build :Self-describing-numbers
dub build :Self-referential-sequence
dub build :Semiprime
dub build :Semordnilap
dub build :Send-email
dub build :Sequence-of-non-squares
dub build :Sequence-of-primes-by-Trial-Division
dub build :Set
dub build :Set-consolidation
dub build :Set-of-real-numbers
dub build :Set-puzzle
dub build :Seven-sided-dice-from-five-sided-dice
dub build :Shell-one-liner
dub build :Short-circuit-evaluation
dub build :Sierpinski-carpet
dub build :Sierpinski-triangle
dub build :Sierpinski-triangle-Graphical
dub build :Sieve-of-Eratosthenes
dub build :Simple-database
dub build :Simple-windowed-application
dub build :Singleton
dub build :Singly-linked-list-Element-definition
dub build :Singly-linked-list-Element-insertion
dub build :Singly-linked-list-Traversal
dub build :Sleep
dub build :Sockets
dub build :Sokoban
dub build :Solve-a-Hidato-puzzle
dub build :Solve-a-Holy-Knights-tour
dub build :Solve-a-Hopido-puzzle
dub build :Solve-a-Numbrix-puzzle
dub build :Solve-the-no-connection-puzzle
dub build :Sort-an-array-of-composite-structures
dub build :Sort-an-integer-array
dub build :Sort-disjoint-sublist
dub build :Sort-using-a-custom-comparator
dub build :Sorting-algorithms-Bead-sort
dub build :Sorting-algorithms-Bogosort
dub build :Sorting-algorithms-Bubble-sort
dub build :Sorting-algorithms-Cocktail-sort
dub build :Sorting-algorithms-Comb-sort
dub build :Sorting-algorithms-Counting-sort
dub build :Sorting-algorithms-Gnome-sort
dub build :Sorting-algorithms-Heapsort
dub build :Sorting-algorithms-Insertion-sort
dub build :Sorting-algorithms-Merge-sort
dub build :Sorting-algorithms-Pancake-sort
dub build :sorting-algorithms-permutation-sort-1
dub build :sorting-algorithms-permutation-sort-2
dub build :Sorting-algorithms-Quicksort
dub build :Sorting-algorithms-Radix-sort
dub build :Sorting-algorithms-Selection-sort
dub build :Sorting-algorithms-Shell-sort
dub build :Sorting-algorithms-Sleep-sort
dub build :Sorting-algorithms-Stooge-sort
dub build :Sorting-algorithms-Strand-sort
dub build :Soundex
dub build :Sparkline-in-unicode
dub build :Spiral-matrix
dub build :Stable-marriage-problem
dub build :Stack
dub build :Stack-traces
dub build :Stair-climbing-puzzle
dub build :Standard-deviation
dub build :State-name-puzzle
dub build :Statistics-Basic
dub build :Stem-and-leaf-plot
dub build :Stern-Brocot-sequence
dub build :String-append
dub build :String-case
dub build :String-comparison
dub build :String-concatenation
dub build :String-interpolation--included-
dub build :String-length
dub build :String-matching
dub build :String-prepend
dub build :Strip-a-set-of-characters-from-a-string
dub build :Strip-block-comments
dub build :Strip-comments-from-a-string
dub build :Strip-control-codes-and-extended-characters-from-a-string
dub build :Strip-whitespace-from-a-string-Top-and-tail
dub build :Substring
dub build :Substring-Top-and-tail
dub build :Subtractive-generator
dub build :Sudoku
dub build :Sum-and-product-of-an-array
dub build :Sum-digits-of-an-integer
dub build :Sum-multiples-of-3-and-5
dub build :Sum-of-a-series
dub build :Sum-of-squares
dub build :Sutherland-Hodgman-polygon-clipping
dub build :Symmetric-difference
dub build :Synchronous-concurrency
dub build :System-time
dub build :Take-notes-on-the-command-line
dub build :Temperature-conversion
dub build :Terminal-control-Clear-the-screen
dub build :Terminal-control-Coloured-text
dub build :Terminal-control-Display-an-extended-character
dub build :Terminal-control-Ringing-the-terminal-bell
dub build :Ternary-logic
dub build :Test-a-function
dub build :Text-processing-1
dub build :Text-processing-2
dub build :Text-processing-Max-licenses-in-use
dub build :Textonyms
dub build :The-ISAAC-Cipher
dub build :The-Twelve-Days-of-Christmas
dub build :Thieles-interpolation-formula
dub build :Tic-tac-toe
dub build :Time-a-function
dub build :Tokenize-a-string
dub build :Top-rank-per-group
dub build :Topological-sort
dub build :topswops-1
dub build :topswops-2
dub build :Total-circles-area
dub build :Towers-of-Hanoi
dub build :Trabb-Pardo-Knuth-algorithm
dub build :Tree-traversal
dub build :Trigonometric-functions
dub build :Truncatable-primes
dub build :Truncate-a-file
dub build :Twelve-statements
dub build :URL-decoding
dub build :URL-encoding
dub build :Ulam-spiral--for-primes-
dub build :Unbias-a-random-generator
dub build :Undefined-values
dub build :Unicode-variable-names
dub build :Universal-Turing-machine
dub build :Unix-ls
dub build :Update-a-configuration-file
dub build :Use-another-language-to-call-a-function
dub build :User-input-Text
dub build :Vampire-number
dub build :Van-der-Corput-sequence
dub build :Variable-length-quantity
dub build :Variable-size-Get
dub build :Variable-size-Set
dub build :Variables
dub build :Variadic-function
dub build :Vector-products
dub build :Verify-distribution-uniformity-Chi-squared-test
dub build :Verify-distribution-uniformity-Naive
dub build :Vigen-re-cipher
dub build :Vigen-re-cipher-Cryptanalysis
dub build :Visualize-a-tree
dub build :Vogels-approximation-method
dub build :Voronoi-diagram
dub build :Walk-a-directory-Non-recursively
dub build :Walk-a-directory-Recursively
dub build :Web-scraping
dub build :Window-creation
dub build :Wireworld
dub build :Word-wrap
dub build :World-Cup-group-stage
dub build :Write-float-arrays-to-a-text-file
dub build :Write-language-name-in-3D-ASCII
dub build :XML-DOM-serialization
dub build :XML-Input
dub build :XML-Output
dub build :XML-XPath
dub build :Xiaolin-Wus-line-algorithm
dub build :Y-combinator
dub build :Yahoo--search-interface
dub build :Yin-and-yang
dub build :Zebra-puzzle
dub build :Zeckendorf-number-representation
dub build :Zero-to-the-zero-power
dub build :Zhang-Suen-thinning-algorithm
dub build :Zig-zag-matrix